version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: "develop"
  ignore:
    - dependency-name: "sorbet"
      update-types: ["version-update:semver-minor", "version-update:semver-patch"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: "develop"